{{- if index .Values "redis-standalone" "enabled" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "agenticore.fullname" . }}-redis
  labels:
    {{- include "agenticore.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}-redis
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}-redis
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: redis
          image: {{ index .Values "redis-standalone" "image" }}
          ports:
            - containerPort: {{ index .Values "redis-standalone" "port" }}
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    {{- include "agenticore.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
    - port: {{ index .Values "redis-standalone" "port" }}
      targetPort: {{ index .Values "redis-standalone" "port" }}
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}-redis
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
