apiVersion: v1
kind: Service
metadata:
  name: {{ include "agenticore.fullname" . }}
  labels:
    {{- include "agenticore.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.server.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "agenticore.selectorLabels" . | nindent 4 }}
