apiVersion: v1
kind: Service
metadata:
  name: agenticore
  labels:
    app: agenticore
spec:
  type: LoadBalancer
  selector:
    app: agenticore
  ports:
  - port: 8200
    targetPort: 8200
    name: http
