apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "agenticore.fullname" . }}-shared
  labels:
    {{- include "agenticore.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.storage.className }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
