apiVersion: v1
kind: Service
metadata:
  name: {{ include "agenticore.fullname" . }}
  labels:
    {{- include "agenticore.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "agenticore.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.config.port }}
      protocol: TCP
